// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href="/api-docs/sell/account/overview.html#requirements">Account API requirements and restrictions</a>.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.ebay.com/sell/account/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List custom policies
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved custom policies 
    remote isolated function getCustomPolicies(map<string|string[]> headers = {}, *GetCustomPoliciesQueries queries) returns CustomPolicyResponse|error {
        string resourcePath = string `/custom_policy/`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a custom policy
    #
    # + headers - Headers to be sent with the request 
    # + payload - Request to create a new Custom Policy 
    # + return - Created 
    remote isolated function createCustomPolicy(CreateCustomPolicyHeaders headers, CustomPolicyCreateRequest payload) returns record {}|error {
        string resourcePath = string `/custom_policy/`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a custom policy
    #
    # + customPolicyId - This path parameter is the unique identifier of the custom policy to retrieve.<br><br> This ID can be retrieved for a custom policy by using the <a href="/api-docs/sell/account/resources/custom_policy/methods/getCustomPolicies" target="_blank ">getCustomPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + return - The retrieved custom policy 
    remote isolated function getCustomPolicy(string customPolicyId, map<string|string[]> headers = {}) returns CustomPolicy|error {
        string resourcePath = string `/custom_policy/${getEncodedUri(customPolicyId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a custom policy
    #
    # + customPolicyId - This path parameter is the unique identifier of the custom policy to update.<br><br><span class="tablenote"><b>Note:</b> A list of custom policies defined for a seller's account that includes this ID can be retrieved by calling the <a href="/api-docs/sell/account/resources/custom_policy/methods/getCustomPolicies" target="_blank ">getCustomPolicies</a> method.</span>
    # + headers - Headers to be sent with the request 
    # + payload - Request to update a current custom policy 
    # + return - No Content 
    remote isolated function updateCustomPolicy(string customPolicyId, UpdateCustomPolicyHeaders headers, CustomPolicyRequest payload) returns error? {
        string resourcePath = string `/custom_policy/${getEncodedUri(customPolicyId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Create a fulfillment policy
    #
    # + headers - Headers to be sent with the request 
    # + payload - Request to create a seller account fulfillment policy 
    # + return - Created 
    remote isolated function createFulfillmentPolicy(CreateFulfillmentPolicyHeaders headers, FulfillmentPolicyRequest payload) returns SetFulfillmentPolicyResponse|error {
        string resourcePath = string `/fulfillment_policy/`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a fulfillment policy
    #
    # + fulfillmentPolicyId - This path parameter specifies the ID of the fulfillment policy you want to retrieve.<br><br> This ID can be retrieved for a fulfillment policy by using the <a href="/api-docs/sell/account/resources/fulfillment_policy/methods/getFulfillmentPolicies" target="_blank ">getFulfillmentPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + return - The retrieved fulfillment policy 
    remote isolated function getFulfillmentPolicy(string fulfillmentPolicyId, map<string|string[]> headers = {}) returns FulfillmentPolicy|error {
        string resourcePath = string `/fulfillment_policy/${getEncodedUri(fulfillmentPolicyId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a fulfillment policy
    #
    # + fulfillmentPolicyId - This path parameter specifies the ID of the fulfillment policy you want to update.<br><br>This ID can be retrieved for a specific fulfillment policy by using the <a href="/api-docs/sell/account/resources/fulfillment_policy/methods/getFulfillmentPolicies" target="_blank ">getFulfillmentPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + payload - Fulfillment policy request 
    # + return - OK 
    remote isolated function updateFulfillmentPolicy(string fulfillmentPolicyId, UpdateFulfillmentPolicyHeaders headers, FulfillmentPolicyRequest payload) returns SetFulfillmentPolicyResponse|error {
        string resourcePath = string `/fulfillment_policy/${getEncodedUri(fulfillmentPolicyId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a fulfillment policy
    #
    # + fulfillmentPolicyId - This path parameter specifies the ID of the fulfillment policy to delete.<br><br> This ID can be retrieved for a fulfillment policy by using the <a href="/api-docs/sell/account/resources/fulfillment_policy/methods/getFulfillmentPolicies" target="_blank ">getFulfillmentPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + return - No Content 
    remote isolated function deleteFulfillmentPolicy(string fulfillmentPolicyId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/fulfillment_policy/${getEncodedUri(fulfillmentPolicyId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # List fulfillment policies
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved fulfillment policies 
    remote isolated function getFulfillmentPolicies(GetFulfillmentPoliciesHeaders headers = {}, *GetFulfillmentPoliciesQueries queries) returns FulfillmentPolicyResponse|error {
        string resourcePath = string `/fulfillment_policy`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get a fulfillment policy by name
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved fulfillment policy by name 
    remote isolated function getFulfillmentPolicyByName(GetFulfillmentPolicyByNameHeaders headers = {}, *GetFulfillmentPolicyByNameQueries queries) returns FulfillmentPolicy|error {
        string resourcePath = string `/fulfillment_policy/get_by_policy_name`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List payment policies
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved payment policies 
    remote isolated function getPaymentPolicies(GetPaymentPoliciesHeaders headers = {}, *GetPaymentPoliciesQueries queries) returns PaymentPolicyResponse|error {
        string resourcePath = string `/payment_policy`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a payment policy
    #
    # + headers - Headers to be sent with the request 
    # + payload - Payment policy request 
    # + return - Created 
    remote isolated function createPaymentPolicy(CreatePaymentPolicyHeaders headers, PaymentPolicyRequest payload) returns SetPaymentPolicyResponse|error {
        string resourcePath = string `/payment_policy`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a payment policy
    #
    # + paymentPolicyId - This path parameter specifies the ID of the payment policy you want to retrieve. <br><br> This ID can be retrieved for a payment policy by using the <a href="/api-docs/sell/account/resources/payment_policy/methods/getPaymentPolicies" target="_blank ">getPaymentPolices</a> method
    # + headers - Headers to be sent with the request 
    # + return - The retrieved payment policy 
    remote isolated function getPaymentPolicy(string paymentPolicyId, map<string|string[]> headers = {}) returns PaymentPolicy|error {
        string resourcePath = string `/payment_policy/${getEncodedUri(paymentPolicyId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a payment policy
    #
    # + paymentPolicyId - This path parameter specifies the ID of the payment policy you want to update. <br><br> This ID can be retrieved for a payment policy by using the <a href="/api-docs/sell/account/resources/payment_policy/methods/getPaymentPolicies" target="_blank ">getPaymentPolices</a> method
    # + headers - Headers to be sent with the request 
    # + payload - Payment policy request 
    # + return - OK 
    remote isolated function updatePaymentPolicy(string paymentPolicyId, UpdatePaymentPolicyHeaders headers, PaymentPolicyRequest payload) returns SetPaymentPolicyResponse|error {
        string resourcePath = string `/payment_policy/${getEncodedUri(paymentPolicyId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a payment policy
    #
    # + paymentPolicyId - This path parameter specifies the unique identifier of the payment policy you want to delete.<br><br> This ID can be retrieved for a payment policy by using the <a href="/api-docs/sell/account/resources/payment_policy/methods/getPaymentPolicies" target="_blank ">getPaymentPolices</a> method
    # + headers - Headers to be sent with the request 
    # + return - No Content 
    remote isolated function deletePaymentPolicy(string paymentPolicyId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/payment_policy/${getEncodedUri(paymentPolicyId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a payment policy by name
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved payment policy by name 
    remote isolated function getPaymentPolicyByName(GetPaymentPolicyByNameHeaders headers = {}, *GetPaymentPolicyByNameQueries queries) returns PaymentPolicy|error {
        string resourcePath = string `/payment_policy/get_by_policy_name`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get payments program status
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace of the payments program for which you want to retrieve the seller's status
    # + paymentsProgramType - This path parameter specifies the payments program whose status is returned by the call
    # + headers - Headers to be sent with the request 
    # + return - The retrieved payments program 
    remote isolated function getPaymentsProgram(string marketplaceId, string paymentsProgramType, map<string|string[]> headers = {}) returns PaymentsProgramResponse|error {
        string resourcePath = string `/payments_program/${getEncodedUri(marketplaceId)}/${getEncodedUri(paymentsProgramType)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get payments program onboarding status
    #
    # + marketplaceId - The eBay marketplace ID associated with the onboarding status to retrieve
    # + paymentsProgramType - The type of payments program whose status is returned by the method
    # + headers - Headers to be sent with the request 
    # + return - The retrieved payments program onboarding 
    remote isolated function getPaymentsProgramOnboarding(string marketplaceId, string paymentsProgramType, map<string|string[]> headers = {}) returns PaymentsProgramOnboardingResponse|error {
        string resourcePath = string `/payments_program/${getEncodedUri(marketplaceId)}/${getEncodedUri(paymentsProgramType)}/onboarding`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get seller privileges
    #
    # + headers - Headers to be sent with the request 
    # + return - The retrieved privileges 
    remote isolated function getPrivileges(map<string|string[]> headers = {}) returns SellingPrivileges|error {
        string resourcePath = string `/privilege`;
        return self.clientEp->get(resourcePath, headers);
    }

    # List opted-in programs
    #
    # + headers - Headers to be sent with the request 
    # + return - The retrieved opted in programs 
    remote isolated function getOptedInPrograms(map<string|string[]> headers = {}) returns Programs|error {
        string resourcePath = string `/program/get_opted_in_programs`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Opt in to a program
    #
    # + headers - Headers to be sent with the request 
    # + payload - Program being opted-in to 
    # + return - The seller was opted in to the program 
    remote isolated function optInToProgram(OptInToProgramHeaders headers, Program payload) returns record {}|error {
        string resourcePath = string `/program/opt_in`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Opt out of a program
    #
    # + headers - Headers to be sent with the request 
    # + payload - Program being opted-out of 
    # + return - The seller was opted out of the program 
    remote isolated function optOutOfProgram(OptOutOfProgramHeaders headers, Program payload) returns record {}|error {
        string resourcePath = string `/program/opt_out`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # List shipping rate tables
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved rate tables 
    remote isolated function getRateTables(map<string|string[]> headers = {}, *GetRateTablesQueries queries) returns RateTableResponse|error {
        string resourcePath = string `/rate_table`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # List return policies
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved return policies 
    remote isolated function getReturnPolicies(GetReturnPoliciesHeaders headers = {}, *GetReturnPoliciesQueries queries) returns ReturnPolicyResponse|error {
        string resourcePath = string `/return_policy`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a return policy
    #
    # + headers - Headers to be sent with the request 
    # + payload - Return policy request 
    # + return - Created 
    remote isolated function createReturnPolicy(CreateReturnPolicyHeaders headers, ReturnPolicyRequest payload) returns SetReturnPolicyResponse|error {
        string resourcePath = string `/return_policy`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a return policy
    #
    # + returnPolicyId - This path parameter specifies the unique identifier of the return policy you want to retrieve. <br><br> This ID can be retrieved for a return policy by using the <a href="/api-docs/sell/account/resources/return_policy/methods/getReturnPolicies" target="_blank ">getReturnPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + return - The retrieved return policy 
    remote isolated function getReturnPolicy(string returnPolicyId, map<string|string[]> headers = {}) returns ReturnPolicy|error {
        string resourcePath = string `/return_policy/${getEncodedUri(returnPolicyId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a return policy
    #
    # + returnPolicyId - This path parameter specifies the ID of the return policy you want to update. <br><br> This ID can be retrieved for a return policy by using the <a href="/api-docs/sell/account/resources/return_policy/methods/getReturnPolicies" target="_blank ">getReturnPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + payload - Container for a return policy request 
    # + return - OK 
    remote isolated function updateReturnPolicy(string returnPolicyId, UpdateReturnPolicyHeaders headers, ReturnPolicyRequest payload) returns SetReturnPolicyResponse|error {
        string resourcePath = string `/return_policy/${getEncodedUri(returnPolicyId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a return policy
    #
    # + returnPolicyId - This path parameter specifies the unique identifier of the return policy you want to delete.<br><br> This ID can be retrieved for a return policy by using the <a href="/api-docs/sell/account/resources/return_policy/methods/getReturnPolicies" target="_blank ">getReturnPolicies</a> method
    # + headers - Headers to be sent with the request 
    # + return - No Content 
    remote isolated function deleteReturnPolicy(string returnPolicyId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/return_policy/${getEncodedUri(returnPolicyId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a return policy by name
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved return policy by name 
    remote isolated function getReturnPolicyByName(GetReturnPolicyByNameHeaders headers = {}, *GetReturnPolicyByNameQueries queries) returns ReturnPolicy|error {
        string resourcePath = string `/return_policy/get_by_policy_name`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Bulk create or replace sales tax entries
    #
    # + headers - Headers to be sent with the request 
    # + payload - List of sales taxes to be updated 
    # + return - The result of each sales tax entry in the bulk request 
    remote isolated function bulkCreateOrReplaceSalesTax(BulkSalesTaxInput payload, map<string|string[]> headers = {}) returns UpdatedSalesTaxResponse|error? {
        string resourcePath = string `/bulk_create_or_replace_sales_tax`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a sales tax entry
    #
    # + countryCode - This path parameter specifies the two-letter <a href="https://www.iso.org/iso-3166-country-codes.html " title="https://www.iso.org " target="_blank">ISO 3166</a> code for the country whose sales tax table you want to retrieve.<br><br><span class="tablenote"><b>Note:</b> Sales-tax tables are available only for the US and Canada marketplaces. Therefore, the only supported values are:<ul><li><code>US</code></li><li><code>CA</code></li></ul></span>
    # + jurisdictionId - This path parameter specifies the ID of the sales tax jurisdiction for the tax table entry to be retrieved.<br><br>Valid jurisdiction IDs can be retrieved using the <a href="/api-docs/sell/metadata/resources/country/methods/getSalesTaxJurisdictions" target="_blank ">getSalesTaxJurisdiction</a> method of the Metadata API.<br><br><span class="tablenote"><b>Note:</b> When <code>countryCode</code> is set to <code>US</code>, the only supported values for <code>jurisdictionId</code> are:<ul><li><code>AS</code> (American Samoa)</li><li><code>GU</code> (Guam</li><li><code>MP</code> Northern Mariana Islands</li><li><code>PW (Palau)</li><li><code>VI</code> (US Virgin Islands)</li></ul></span>
    # + headers - Headers to be sent with the request 
    # + return - The retrieved sales tax 
    remote isolated function getSalesTax(string countryCode, string jurisdictionId, map<string|string[]> headers = {}) returns SalesTax|error? {
        string resourcePath = string `/sales_tax/${getEncodedUri(countryCode)}/${getEncodedUri(jurisdictionId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Create or replace a sales tax entry
    #
    # + countryCode - This path parameter specifies the two-letter <a href="https://www.iso.org/iso-3166-country-codes.html " title="https://www.iso.org " target="_blank">ISO 3166</a> code for the country for which you want to create a sales tax table entry.<br><br><span class="tablenote"><b>Note:</b> Sales-tax tables are available only for the US and Canada marketplaces. Therefore, the only supported values are:<ul><li><code>US</code></li><li><code>CA</code></li></ul></span>
    # + jurisdictionId - This path parameter specifies the ID of the tax jurisdiction for the table entry to be created.<br><br>Valid jurisdiction IDs can be retrieved using the <a href="/api-docs/sell/metadata/resources/country/methods/getSalesTaxJurisdictions" target="_blank ">getSalesTaxJurisdiction</a> method of the Metadata API.<br><br><span class="tablenote"><b>Note:</b> When <code>countryCode</code> is set to <code>US</code>, the only supported values for <code>jurisdictionId</code> are:<ul><li><code>AS</code> (American Samoa)</li><li><code>GU</code> (Guam)</li><li><code>MP</code> (Northern Mariana Islands)</li><li><code>PW</code> (Palau)</li><li><code>VI</code> (US Virgin Islands)</li></ul></span>
    # + headers - Headers to be sent with the request 
    # + payload - A container that describes the how the sales tax is calculated 
    # + return - No Content 
    remote isolated function createOrReplaceSalesTax(string countryCode, string jurisdictionId, CreateOrReplaceSalesTaxHeaders headers, SalesTaxBase payload) returns error? {
        string resourcePath = string `/sales_tax/${getEncodedUri(countryCode)}/${getEncodedUri(jurisdictionId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a sales tax entry
    #
    # + countryCode - This path parameter specifies the two-letter <a href="https://www.iso.org/iso-3166-country-codes.html " title="https://www.iso.org " target="_blank">ISO 3166</a> code for the country whose sales tax table entry you want to delete.<br><br><span class="tablenote"><b>Note:</b> Sales-tax tables are available only for the US and Canada marketplaces. Therefore, the only supported values are:<ul><li><code>US</code></li><li><code>CA</code></li></ul></span>
    # + jurisdictionId - This path parameter specifies the ID of the sales tax jurisdiction whose table entry you want to delete.<br><br>Valid jurisdiction IDs can be retrieved using the <a href="/api-docs/sell/metadata/resources/country/methods/getSalesTaxJurisdictions" target="_blank ">getSalesTaxJurisdiction</a> method of the Metadata API.<br><br><span class="tablenote"><b>Note:</b> When <code>countryCode</code> is set to <code>US</code>, the only supported values for <code>jurisdictionId</code> are:<ul><li><code>AS</code> (American Samoa)</li><li><code>GU</code> (Guam)</li><li><code>MP</code> (Northern Mariana Islands)</li><li><code>PW</code> (Palau)</li><li><code>VI</code> (US Virgin Islands)</li></ul></span>
    # + headers - Headers to be sent with the request 
    # + return - Success 
    remote isolated function deleteSalesTax(string countryCode, string jurisdictionId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/sales_tax/${getEncodedUri(countryCode)}/${getEncodedUri(jurisdictionId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # List sales tax entries
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved sales taxes 
    remote isolated function getSalesTaxes(map<string|string[]> headers = {}, *GetSalesTaxesQueries queries) returns SalesTaxes|error {
        string resourcePath = string `/sales_tax`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # List seller subscriptions
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved subscription 
    remote isolated function getSubscription(map<string|string[]> headers = {}, *GetSubscriptionQueries queries) returns SubscriptionResponse|error {
        string resourcePath = string `/subscription`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get seller KYC status
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getKYC(map<string|string[]> headers = {}) returns KycResponse|error? {
        string resourcePath = string `/kyc`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get advertising eligibility
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved advertising eligibility 
    remote isolated function getAdvertisingEligibility(GetAdvertisingEligibilityHeaders headers, *GetAdvertisingEligibilityQueries queries) returns SellerEligibilityMultiProgramResponse|error {
        string resourcePath = string `/advertising_eligibility`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
